title: UACheckBot&nbsp;&mdash; чек у два дотики
description: >
  UACheckBot&nbsp;&mdash; найпростіший та найшвидший інструмент для створення чеків в Україні
url: https://uacheckbot.github.io

bot_name: "@UACheckBot"
bot_url: https://t.me/UACheckBot

ref_name: checkbox.ua
ref_url: https://my.checkbox.ua/auth/registration?partner_ref=jSRBBchknW

copy_year: 2021
copy_name: Олександр Тішин

facebook: https://facebook.com/UACheckBot

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - .idea

gems:
  - jekyll-tidy
